name: clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Clang Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'stuffer'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
